enC = {
    "child_porn" : ['child porn', 'child sexual abuse', 'child', 'interpol', 'united states department of justice', 'pornography', 'video', 'sound recording, minor', 'pedophilia', 'child grooming', 'european commission', 'internet watch foundation', 'united states reports', 'law', 'photograph', 'sculpture', 'drawing', 'photography', 'painting', 'animation', 'coercion', 'censorship', 'clothing', 'lolicon', 'nudity', 'camera', 'massachusetts', 'recording'],

    "bitcoin" : ['bitcoin', 'blockchain', 'currency', 'bitcoin network', 'cryptography', 'node', 'satoshi nakamoto', 'open-source software', 'cryptocurrency wallet', 'cryptocurrency exchange', 'cryptocurrency', 'public-key cryptography', 'ethereum', 'qt', 'central bank', 'distributed ledger', 'university of cambridge', 'nobel memorial prize in economic sciences', 'gavin andresen', 'silk road', 'youtube', 'segwit', 'kraken', 'ledger', 'financial crimes enforcement network', 'forth', 'double-spending', 'lightning network', 'bitcoin cash', 'unit of account', 'digital signature', 'cryptographic hash', 'megabyte', 'winklevoss twins', 'synchronization', 'bitcoin xt', 'baidu', 'proof-of-concept', 'cve', 
                'leveldb', 'nyse', 'micropayment', 'openssl', 'andreas antonopoulos', 'bitinstant', 'unicode', 'broadcasting', 'banknote', 'malleability'],

    "drug" : ['drug', 'medicine', 'dope', 'psychoactive drug', 'medication', 'dose', 'stimulant', 'narcotic', 'injectable', 'pharmaceutical', 'pharmacy', 'analgesic', 'prescription', 'prescription drug', 'alcohol', 'drop', 'absorption', 'antisyphilitic', 'abortifacient', 'medicate', 'addiction', 'medicament', 'aspirin', 'tobacco', 'cannabis', 'fertility drug', 'narcotize', 'pharmaceutical drug', 'smoking', 'magic bullet', 'generic', 'antiviral', 'pharmacist', 'preventive medicine', 'physician', 'benzodiazepine', 'do drugs', 'anticonvulsant', 'antidrug', 'generic drug', 'antiemetic', 'probenecid', 'antidepressant', 'antibiotic', 'illegal', 'cocaine', 'marijuana', 'psychoactive substance', 'opiate', 'narcotics', 'heroin', 'amphetamine', 'methamphetamine', 'drug class', 'pills', 'medicines', 'chemical structure', 'mechanism of action', 'caffeine', 'vaccine', 'steroids', 'mode of action', 'cancer', 'anatomical therapeutic chemical classification system', 'atc code', 'biopharmaceutics classification system', 'hallucinogen', 'drug addiction', 'recreational drug use', 'single convention on narcotic drugs', 'who', 'over-the-counter drug', 'ingestion', 'substance', 'druggist', 'pharmacology', 'antihistamine', 'organism', 'codeine', 'anticholinergic', 'antibacterial', 'anticoagulant', 'biomedicine', 'chronic', 'immunology', 'prodrug', 'paregoric', 'food', 'apc', 'oncology', 'therapeutic', 'rheumatology', 'gastroenterology', 'anesthesiology', 'placebo', 'radiotherapy', 'insufflation', 'hypnotic', 'agent', 'relaxant', 'arsenical', 'pharmacopoeia', 'diuretic', 'botanical', 'overdose', 'orally', 'agonist', 'anaphylaxis', 'antagonist', 'anesthetic', 'trip', 'anaesthetic', 'excitant', 'soporific', 'poison', 'base', 'use', 'inject', 'snort', 'nephrology', 'drugs', 'purgative', 'palliative', 'neurology', 'nonspecific', 'panacea', 'therapy', 'pcp', 'clinician', 'laxative', 
                'urology', 'penicillin', 'curative', 'nostrum', 'remedy', 'medical', 'virology', 'dermatology', 'pediatrics', 'catatonic', 'psychiatry', 'gynecology', 'medic', 'nondrug', 'peptic', 'insulin', 'sedation', 'paracetamol', 'refractory', 'dispensary', 'pharmaceutic', 'neurologist', 'allopurinol', 'tiamulin', 'antidiabetic', 'acyclovir', 'opium', 'disulfiram', 'pentylenetetrazol', 'antispasmodic', 'carminative', 'gemfibrozil', 'antidiarrheal', 'decongestant', 'antiprotozoal', 'expectorant', 'md', 'splint', 'premedication', 'antitussive', 'pharmacon', 'physostigmine', 'psychotic', 'isoproterenol', 'medicinal', 'isosorbide', 'amrinone', 'antiarrhythmic', 'potentiation', 'perception', 'immunosuppressant', 'fever', 'clofibrate', 'medicative', 'vermifuge', 'antipyretic', 'sucralfate', 'antihypertensive', 'psychomedicine', 'anticholinesterase', 'mood', 'neurotropic', 'postdrug', 'parenteral', 'premedical', 'neuropsychiatry', 'clonic', 'azathioprine', 'aesculapian', 'venesect', 'traumatology', 'nonprescription', 'urinalysis', 'vermicide', 'penicillamine', 'proctology', 'consciousness', 'lorfan', 'anaesthetize', 'anaesthetise', 'free-base', 'anesthetize', 'uninjectable', 'habituate', 'narcotise', 'potentiate', 'aborticide', 'synergist', 'suppressant', 'dilator', 'feosol', 'fergon', 'o.d.', 'intoxicant', 'trental', 'levallorphan', 'pentoxifylline', 'mydriatic', 'myotic', 'miotic', 'anesthetise', 'podiatry', 'papaverine', 'hematinic', 'leechcraft', 'counterirritant', 'ethanol', 'ethnomedicine', 'suppository', 'mfm', 'pseudomedical', 'iatrophysics', 'polychrest', 'nonmedical', 'noninvasive', 'antidiuretic', 'infection', 'depressant', 'nosology', 'wonderdrug', 'pulmonology', 'bronchodilator', 'panpharmacon', 'nicotine', 'nanomedicine', 'trafficking', 'achromia', 'vasoconstrictor', 'oxytocic', 'phytomedicine', 'succedaneum', 'unguent', 'traffickers', 'digitalize', 'cases', 'zymosis', 'mercurialist', 'rubefacient', 'otology', 'treatment', 'hiv', 'tylenol', 'medications', 'aids', 'linked', 'smuggling'],

    "counterfeit" : ['counterfeit', 'fake', 'false', 'phony', 'bogus', 'forgery', 'spurious', 'sham', 'pseudo', 'imitation', 'scam', 'fraud', 'fictitious', 'forged', 'phoney', 'identity theft', 'unreal', 'insincere', 'handbags', 'forge', 'imitative', 'illegal', 'base', 'bastard', 'fictive', 'mock', 'synthetic', 'assumed', 'pretended', 'pinchbeck', 'bad', 'ostensible', 'fraudulent', 'unauthentic', 'inauthentic', 'ostensive', 'pirated', 'contraband', 'smuggled', 'put on', 'confiscated', 'heroin', 'printing', 'forgeries', 'stolen', 'cocaine', 'illicit', 'counterfeiters', 'banknotes', 'methamphetamine', 'theft', 'jewelry', 'illegally', 'marijuana', 'coins', 'narcotics', 'jewellery', 'knockoffs', 'united states secret service', 'sale', 'currency', 'document', 'clothing', 'shoes', 'falsely', 'falsification', 'pharmaceutical', 'artificial', 'falsity', 'manufacture', 'falseness', 'deception', 'mendacious', 'watch', 'deceit', 'falsify', 'imposture', 'dishonesty', 'untruthful', 'falsehood', 'mendacity', 'charlatan', 'untruth', 'electronics', 'feign', 'delusive', 'untrue', 'mislead', 'deceitful', 'deceiver', 'deceive', 'delude', 'imposter', 'deceptive', 'software', 'delusion', 'hoax', 'misrepresentation', 'trickery', 'fib', 'swindle', 'duplicity', 'dupe', 'liar', 'impostor', 'misrepresent', 'lig', 'art', 'lie', 'defraud', 'cozen', 'chicanery', 'perjure', 'bilk', 'humbug', 'subterfuge', 'forger', 'bask', 'ingenuine', 'cheat', 'deceptively', 'toys', 're-create', 'jugglery', 'pretense', 'trickster', 'guile', 'bamboozle', 'faithlessness', 'swindler', 'falsifier', 'belie', 'fallacious', 'movies', 'insincerity', 'dissimulate', 'perjury', 'amuser', 'unfaithful', 'hocus', 'cheater', 'gullible', 'trick', 'fraudulence', 'shlenter', 'fraudster', 'logos', 'blench', 'mendaciously', 'beguile', 'treacherous', 'embezzlement', 'counterfeiting', 'waylay', 'fakery', 'flimflam', 'whopper', 'brands', 'pretender', 'deceptiveness', 'laity', 'layoff', 'fibbery', 'prevarication', 'hoodwink', 'falsifiable', 'decipiency', 'mislie', 'unlying', 'blag', 'perjurer', 'adulterous', 'counterfeits', 'falsificationism', 'gull', 'rort', 'fool', 'dupery', 'importing', 'forlay', 'finagler', 'copying', 'overreach', 'chouse', 'prevaricate', 'forlie', 'imported', 'befool', 'fakes', 'import', 'hornswoggle', 'blesh', 'undeceive', 'belirt'],

    "murder" : ['murder', 'homicide', 'manslaughter', 'assassination', 'infanticide', 'suicide', 'crime', 'slay', 'slaying', 'kill', 'common law', 'hit', 'bump off', 'dispatch', 'revenge', 'massacre', 'parricide', 'murderer', 'filicide', 'killer', 'thuggee', 'genocide', 'california', 'mutilate', 'remove', 'mangle', 'slaughter', 'mariticide', 'carnage', 'regicide', 'fratricide', 'jurisdiction', 'tyrannicide', 'bloodshed', 'uxoricide', 'execution', 'butchery', 'polish off', 'burke', 'mass murder', 'murderess', 'execute', 'felony', 'victim', 'lynching', 'decapitation', 'patricide', 'kidnapping', 'robbery', 'canada', 'serial' 'killer', 'matricide', 'criminal', 'first degree murder', 'arrest', 'strangulation', 'death', 'abduction', 'conspiracy', 'accomplice', 'conviction', 'killing', 'molestation', 'suspects', 'strangler', 'arson', 'prosecution', 'sentence', 'treason', 'imprisonment', 'disappearance', 'burglary', 'prosecutors', 'extortion', 'assault', 'united states', 'defendant', 'malice aforethought', 'self defense', 'country', 'aggravation', 'off', 'person', 'justification', 'excuse', 'assassinate', 'homicidal', 'slayer', 'assassin', 'murderous', 'deterrence', 'rehabilitation', 'law', 'bloodbath', 'oppression', 'cide', 'decimate', 'slaughterer', 'lynch', 'liquidation', 'distort', 'gore', 'elimination', 'falsify', 'warp', 'exterminator', 'saber', 'poisoner', 'murderee', 'slaught', 'killingly', 'unslain', 'euthanasia', 'murdersome', 'electrocute', 'killbot', 'combatants', 'instakill', 'murderable', 'poison', 'criminalization', 'killable', 'fetus', 'lethal', 'murders', 'vagina', 'electrocution', 'horizontalize', 'accident', 'convicted', 'teamkill', 'guilty', 'obliterable', 'nonkilling', 'manslaying', 'proto-indo-european', 'exterminate', 'garble', 'dry-gulching', 'shoot-down', 'bane', 'anglo-saxon', 'lethality', 'trial', 'sororicide', 'sentenced', 'acquitted', 'pleaded', 'magistricide', 'eradication', 'decimation', 'avenge', 'charged', 'alleged', 'charges', 'butcher', 'poisoning', 'insanity', 'killings', 'crimes', 'murdering', 'self-defence', 'executioner', 'photokilling', 'killjoy', 'confessed', 'invincible', 'non-combatants', 'vengeance', 'winterkill', 'suspect', 'counts', 'precedent', 'killers', 'maniac', 'arrested', 'case', 'codification', 'killology', 'legal', 'democide', 'slaughterhouse', 'cadaver', 'witness', 'innocent', 'stabbing', 'organism', 'murdered', 'theft', 'indictment', 'jail', 'toxin', 'custody', 'femicide', 'simpson', 'slaughterman', 'indicted', 'butch', 'venom', 'involvement', 'poisonous', 'abuse', 'defendants', 'attempted', 'sex', 'adultery', 'suspicion', 'amok'],

    "hack" : ['hack', 'hacker', 'spyware', 'malware', 'rasomeware', 'RAT', 'DataBases Leaks', 'DB Leaks', 'Leak', 'Carding', 'Personal information Leak', 'botnet', 'rootkit', 'adware', 'keylogger',
                'Trojan horse', 'backdoor', 'warm', 'korea Leaks', 'Chinese Leaks', 'japan Leaks'],

    "weapon" : ['weapon', 'sword', 'gun', 'missile', 'spear', 'firearm', 'ammunition', 'artillery', 'projectile', 'rifle', 'pistol', 'bomb', 'bow', 'weaponry', 'arm', 'arms', 'knife', 'munition', 'cannon', 'guns', 'shotgun', 'tool', 'gunpowder', 'rocket', 'weapon system', 'world war ii', 'military', 'hunting', 'instrument', 'pike', 'bronze age', 'firearms', 'tank', 'war', 'machine gun', 'animal', 'fire ship', 'warfare', 'warhead', 'rock', 'armor', 'weapons', 'explosive', 'intercontinental ballistic missile', 'biological warfare, device', 'enemy', 'deterrent', 'sidearm', 'machine', 'caliber', 'firing', 'element', 'type', 'threat', 'target', 'dangerous', 'vehicle', 'warship', 'army', 'fire', 'weapon of mass destruction', 'ammo', 'power', 'armour', 'siege weapon', 'technology during world war i', 'injury', 'crime', 'club', 'teeth', 'axe', 'claw', 'tusk', 'knuckles', 'flamethrower', 'slasher', 'sling', 'lance', 'shaft', 'blade', 'brand', 'steel', 'hatchet', 'tomahawk', 'wmd', 'persuasion', 'suasion', 'stone', 'self-defense', 'hominids', 'bc', 'obsidian', 'neolithic', 'copper', 'metal', 'cyberweapon', 'knucks', 'w.m.d.', 'fortifications', 'catapult', 'spoke', 'chariot', 'china', 'cavalry', 'assault', 'handgun', 'europe', 'capable', 'explosives', 'trireme', 'possessing', 'arsenal', 'bombs', 'missiles', 'lethal', 'capability', 'revolver', 'knights', 'conventional', 'carry', 'nuclear', 'battery', 'ballistic', 'infantry', 'using']
}

koC = {
    "child_porn" : ['아동 포르노', '아동 성학대', '아동', '인터폴', '미국 법무부', '포르노', '비디오', '녹음', '미성년자', '소아성애', '그루밍', '유럽 위원회', '인터넷 워치 재단',
                        '미국 보고서', '법률', '사진', '조각', '드로잉', '사진', '그림', '그림', '애니메이션', '강제', '검열', '옷', '롤리콘', '누드', '카메라', '매사추세츠 주의', '녹음'],

    "bitcoin" : ['비트코인', '블록체인', '화폐', '비트코인 네트워크', '암호학', '노드', '사토시 나카모토', '오픈소스 소프트웨어', '암호화폐 지갑', '암호화폐 거래소', '암호화폐',
                '공개키' '암호학', '이더리움', 'qt', '중앙은행', '분산원장', '케임브리지 대학교', '노벨 경제학상', '가빈 앤 리센', '실크로드', '유투브', '세그윗', 'kraaken',
                '원장', '금융 범죄 집행 네트워크', '넷째', '이중 추적', '번개 네트워크', '비트코인 현금', '계좌 단위', '디지털 서명', '암호화 해시', '메가바이트', '윙클보스 트윈스',
                '동기화', '비트코인 xt', '바이두', '개념 증명', 'CVE','leveldb', 'nyse', 'micropayment', 'openssl', 'andreas 안토노풀로스', '비트인스턴트', '유니코드', '방송', '지폐', '가단성'],

    "drug" : ['마약', '약물', '약물', '약물', '약물', '자극제', '마취제', '주사제', '약', '약', '진통제', '처방약', '알코올', '방울', '흡수', '항염증', '낙태약', '약물', '중독', '약물', '아스피린', '담배',
                '대마초', '불임약', '마약', '마약', '총탄', '유전자ric', '항바이러스제', '약사', '예방의학', '의사', '벤조디아제핀', '약물', '항경련제', '해독제', '일반의약품', '항토제', '프로베네시드',
                '항우울제', '항생제', '불법', '코카인', '마리화나', '정신작용물질', '아편', '마약', '헤로인', '암페타민', '약물류', '약제', '약제', '화학구조', '기계장치 작용', '카페인', '백신',
                '스테로이드', '작용 모드', '암', '해부학적 치료 화학 분류 시스템', 'atc 코드', '생약 분류 시스템', '환각제', '약물 중독', '레크리에이션 약물 사용', '마취약품에 대한 단일 협약',
                '처방전 없이 살 수 있는 약물', '섭취', '물질', '약사', '항히스타민', '오르가nism', 'codine', '항콜린제', '항균제', '항응고제', '생의학', '만성', '면역학', '프로드러그', '식품', 'apc',
                '종양학', '치료', '류머티스학', '소화기내과', '마취과', '플라시보', '방사선 치료', '흡입', '최면제', '이완제', '비소', '약제', '이뇨제', '식물학', '과량', '항응고제', '항응고제', '항응고제',
                '항응고제', '항응고제', '항응고제', '항응고제', '항응고제', '항응고제', '항응고제', '항응고제','탠곤제', '마취제', '트립', '마취제', '흥분제', '최면제', '독약', '베이스', '사용', '주사', '코흘리개',
                '신장내과', '약물', '정화제', '완화제', '신경내과', '비특이적', '만병통치약', '치료제', 'pcp', '임상의사', '설사약', '치료제', '비뇨기과', '페니실린', '치료제', '치료제', '의료', '바이러스학',
                '피부과', '소아과', '심장병', '정신과', '산부인과', '의학', '비약물', '소화제', '인슐린', '진정제', '파라세타몰', '내화약', '약제', '신경과', '알로퓨리놀', '티아물린', '아편', '디술피라미네톨',
                '아편', '아편', '아편', '아편', '소아병', '소아병', '정신병', '소아병', '소아병', '정신병', '소아병', '정신병', '정신병', '소아병', '심장병', '심장병', '심장병', '심장병', '심장병', '심장병', '약물',
                'mfibrozil', '지사제', '충혈방지제', '항원충격제', '기대제', 'md', '부목', '계획제', '진통제', '약제', '이소프로테레놀', '약제', '이소소브라이드', '암리논', '항부정맥제', '퍼텐셔네이션',
                '인식제', '면역억제제제제제', '치료제', '항고혈압제', '항고혈압제', '항고혈압제', '항진통제', '항고혈압제', '항진통제', '항고혈압제', '항진통제', '항염증제', '항진통제', '항진통제',
                '항진통제', '항염제', '항염증제','ine', '항콜린에스테라제', '기분', '신경계', '약물 후', '비경구', '예비의학', '신경정신과', '클리닉', '아자티오프린', '아스쿨라피안', '정맥', '외상', '비처방',
                '소변분석', '해충제', '페니실라민', '항염기', '마취', '마취', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', '마취제', 
                '마취제', '마취제', '마취제산화물', '상승제', '억제제', '확장제', '페오솔', '퍼거슨', 'O.D', '중독제', '트렌탈', '레발로판', '오독시필린', '진통제', '진통제', '진통제', '진통제', '진통제',
                '진통제', '마취제', '파파베린', '혈통제', '거머리', '역자극제', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올', '에탄올',
                '에탄올', '에탄올', '에탄올수지', '노솔로지', '신기한 약', '폐', '기관지' '확장제', '팬파마콘', '니코틴', '나노 의약품', '밀매', '무채색', '혈관 수축제', '옥시토크', '식물 의약품',
                '석세스데넘', '밀매', '디지털화', '사례', '지모시스', '수은주', '루벤젠', '이질', '이질', '이질', '이질', '밀매', '밀매', '밀매', '밀매'],

    "counterfeit" : ['위조', '가짜', '신원도용', '언리얼', '성의 없는', '핸드백', '위조', '모조', '불법', '베이스', '서자', '허구', '가짜', '모의', '합성', '핀치벡', '해적', '착용', '몰수', '헤로인', '인쇄', '위조', '도난', '코카인', '불법', '위조', '지폐', '필로폰', '도난', '보석', '불법', '마리화나', '동전', '마약', '보석', '모조품', '미국 비밀 서비스', '판매', '화폐', '문서', '의류', '신발', '허위', '위조', '제약', '인공', '위조', '제조', 'fa경솔함', '속임수', '거짓', '오도', '기만', '속임', '속임', '소프트웨어', '망상', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓', '거짓','ent', 'lig', '예술', '거짓말', '사기', '사기', '사기', '위증', '빌크', '사기꾼', '속임수', '속임수', '속임수', '속임수', '속임수', '속이기', '장난감', '재창조', '속임수', '속임수', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속이기', '속렌스', '슐렌터', '사기범', '로고', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범', '사기범','ery', '가져오기', '포레이', '피너글러', '복사', '오버 리치', '선택', '프리바리', 'forly', '가져오기', '가져오기', '가져오기', 'hornswoggle', 'blesse', 'undeceive', 'belirt'],

    "murder" : ['살인', '과실치사', '암살', '영아살해', '살인', '자살', '범죄', '살인', '살인', '파견', '학살', '학살', '살인자', '폭력배', '대량학살', '살인범', '대량학살', '캘리포니아', '토막살해', '제거', '남성살해', '해양살해', '대학살해', '재판관할권', '폭동살해', '유혈', '집행권이온', '도살', '광택제', '버크', '대량살해', '살인', '처형', '중죄', '피해자', '린치', '참수', '패트리어트', '납치', '강도', '캐나다', '연쇄살인범', '모살', '범죄자', '1급살해', '체포', '목 졸라', '죽음', '납치', '음모', '공범', '유죄판결', '추행', '추행', '용의자', '목 졸라', '방화', '기소', '선고ce', '반역', '감금', '실종', '강도', '검사', '강탈', '폭행', '미국', '피고', '악의적 사전', '자기방어', '국가', '분노', 'off', '사람', '정당성', '변명', '암살', '살인', '살인', '살인', '살인', '살인', '억지', '회생', '법', '피바다', '살인', '학살자', '학살자', '린치', 'll액화', '왜곡', '고어', '제거', '위조', '워프', '말살', '세이버', '독극물', '살육', '비종교', '안락사', '킬썸', '감전', '킬봇', '전투원', '인스타킬', '살생', '살생', '살생', '살생', '살생', '살생', '질', '감전', '수평화', '사고', '유죄', '팀킬', '말살', '말살', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인', '살인','ble', 'non-killing', 'manslaying',' proto-indo-european', '몰살', '가글', '드라이-gulching', '총격', '베인', '앵글로-글론', '치사', '재판', '소로살', '선고', '무죄', '재판', '기소', '무죄', '재판', '재판', '기소', '기소', '무죄', '재판', '재판', '재판', '재판', '기소', '기소', '도살', '도살', '도살', '독살', '독살', '독살', '살인', '사형', '살인', '사형', '사형', '사형', '사형', '살인', '사형', '사형', '사형', '사형', '사형', '사형', '사형', '사형', '사형', '사형', '킬조이', '자백', '무적', '무적', '복수', '겨울' '살인', '용의자', '카운트', '판례', '킬러', '미치광이', '체포', '사건', '코드화', '킬로지', '소송', '범죄', '도살장', '시체', '목격자', '무죄', ''칼'부림', '유기체', '살해', '절도', '기소', '독소', '감호', '독소', '심슨', '도살장', '기소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '기소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독소', '독횡령', '독극물', '학대', '피고인', '미수', '섹스', '간통', '의심', '장난'],

    "hack" : ['해커', '해커', '스파이웨어', '악성 프로그램', 'RAT', '데이터 베이스 판매', 'DB 판매', 'DB 유출', 'Carding', '개인 정보 판매', '봇넷', '루트킷', '애드웨어', '키로거',
                '트로이 목마', '백도어', '웜', '한국 DB 판매', '중국 DB 판매', '일본 DB 판매'],

    "weapon" : ['무기', '칼', '총', '미사일', '창', '화기', '탄약', '포', '발사체', '소총', '권총', '폭탄', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '제2차 세계 대전', '군사', '사냥', '기구', '청동기 시대', '무기', '탱크', '기관총', '동물', '화약', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기', '무기또는 무기', '폭발물', '대륙간탄도미사일', '생물전', '장치', '적', '억지력', '사이드암', '기계', '구경', '사격', '요소', '종류', '위협', '표적', '위험', '차량', '군함', '군함', '화기', '탄약', '전력', '장갑', '공성 무기', '기술', '세계 대전 중의 기술', '부상', '클럽', '이빨', '발톱', '발톱', '손가락 마디', '화염방사기', '슬래셔', '슬래셔', '랜스', '샤프트', '브랜드', '스틸', '도끼', 'wmd', '설득', '설득', '돌', '정당방위', '호민관', 'bc', '흑요석', '신석기', '구리', '금속', '사이버 무기', 'nucks', 'w.d', '요새', '캐터펄트', '말', '전차', '중국', '기병', '공격', '유럽', '폭발물', '유럽', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물', '폭발물센서', '폭탄', '미사일', '필살기', '능력', '리볼버', '기사', '재래식', '운반', '핵', '배터리', '탄도', '보병', '사용']
}

jaC = {
    "child_porn" : [児童ポルノ,児童性的虐待,児童,インターポール,アメリカ合衆国司法省,ポルノ,ビデオ,録音,未成年,小児愛,児童グルーミング,ヨーロッパ委員会,インターネットウォッチ財団,アメリカ合衆国の報告,法律,写真,彫刻,絵,アニメ,検閲,服,lolicon,nude,camera,massachusetts,録音],

    "bitcoin" : [ビットコイン、ブロックチェーン、通貨、ビットコインネットワーク、暗号化、ノード、サトシナカモト、オープンソースソフトウェア、暗号通貨ウォレット、暗号通貨取引所、暗号通貨、公開鍵暗号化、イーサリアム、qt、中央銀行、分散元帳、ケンブリッジ大学、ノーベル経済学賞、ギャビンアンドレセン、シルクロード、youtube、segwit,kraken,元帳,金融犯罪執行ネットワーク,four,ダブルクリック,ライトニングネットワーク,ビットコインキャッシュ,アカウント単位,デジタル署名,暗号ハッシュ,メガバイト,ウィンクルボス双生児,同期,ビットコインxt,baidu,概念証明,cve,
                                levelb,nyse,マイクロペイメント,openssl,andasantonopoulos,bitinstant,Unicode,ブロードキャスト,banknote,可鍛性],

    "drug" : [医薬品,医薬品,ドーピング,精神活性剤,医薬品,覚醒剤,麻薬,注射可能,医薬品,薬局,鎮痛剤,処方薬,処方薬,アルコール,ドロップ,吸収,抗炎症薬,中絶薬,医薬品,中毒,医薬品,アスピリン,タバコ,大麻,不妊薬,麻薬,喫煙,魔法の弾丸, ジェネリック、抗ウイルス剤、薬剤師、予防医学、医師、ベンゾジアゼピン、薬物、抗痙攣剤、抗薬、ジェネリック医薬品、制吐剤、プロベネシド、抗うつ剤、抗生物質、違法、コカイン、マリファナ、精神活性物質、オピエート、麻薬、ヘロイン、アンフェタミン、メタンフェタミン、薬物クラス、錠剤、薬、化学構造、機械作用のイズム、カフェイン、ワクチン、ステロイド、作用モード、がん、解剖学的治療化学分類システム、atcode、バイオ医薬品分類システム、幻覚剤、薬物中毒、レクリエーション薬物使用、麻酔薬に関する単一条約、市販薬、摂取、物質、薬剤師、薬剤学、抗ヒスタミン薬, 生物,コデイン,抗コリン剤,抗菌剤,抗凝固剤,生物医学,慢性,免疫学,プロドラッグ,パレゴリック,食品,apc,腫瘍学,治療学,リウマチ学,消化器内科,麻酔学,プラセボ,放射線療法,吸入,催眠,薬剤,リラクセンダント,ヒ素,利尿剤,植物学,過剰摂取,経口投与,アゴニスト,アナフィラート,アナフィラートxis,拮抗薬,麻酔薬,トリップ,麻酔薬,興奮剤,睡眠薬,毒,塩基,使用,注射,鼻息,腎臓内科,薬,煉獄,緩和剤,神経内科,非特異的,万病薬,セラピー,pcp,臨床医,下剤,
                        泌尿器科,ペニシリン,治療薬,鼻腔,治療薬,医療,ウイルス学,皮膚科,小児科,カタトニック,精神科,婦人科,医学,非薬物,ペプチド,インスリン,鎮静,パラセタモール,耐火物,調剤,薬学,神経科,アロプリノール,チアムリン,抗糖尿薬,アシクロビル,アヘン,ジスルフィラム,ペンテトラゾール,抗けいれん薬, 駆虫剤,ジェムフィブロジル,下痢止め,抗凝固剤,抗原剤,期待薬,md,添え木,計画薬,抗痙攣剤,薬剤,ファーマコン,フィソスチグミン,精神病,イソプロテノール,医薬品,イソソルビド,アミノン,抗不整脈剤,増強剤,知覚剤,免疫抑制剤,発熱剤,クロフィブラート,医薬品,ベリファージ,解熱剤,スクラルフェート,抗高血圧薬アイブ,精神医学,抗コリンエステラーゼ,気分,ニューロトロピック,後薬,非経口,前薬,神経精神医学,クローン,アザチオプリン,イソプラピアン,静脈,外傷学,非処理学,尿検査,バーミジル,ペニシラミン,プロクトロジー,意識,ローファン,麻酔薬,自由基底,麻酔薬,注射できない,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,麻酔薬,触診、中絶、相乗効果、抑制剤、拡張剤、フェオソール、ファーゴン、o.d.、中毒、トレント、レヴァロルファン、ペントキシフェリン、散発性、ミオティック、麻酔、ポディアトリー、パパベリン、ヘマチン、ヒルクラフト、抗刺激剤、エタノール、エスノメジック、坐薬、mfm、偽薬、イトロフィジカル、ポリクレスト、非医療、非侵襲的、抗利薬, 感染,うつ病,ノソロジー,ワンダードラッグ,肺活物質,気管支拡張剤,パンファーマコン,ニコチン,ナノ医薬品,トランキング,クロミア,血管収縮剤,オキシトシン,フィトメジック,サクセダヌス,アンガント,トラッカー,デジタル化,症例,ジモシス,水銀学者,ルベファシエンティスト,オトロジー,治療,hiv,tylenol,医薬品,リンク,密輸],

    "counterfeit" : [偽造、偽、偽、偽、偽、偽、偽、偽、偽、偽、偽、偽、偽、模倣、詐欺、詐欺、架空、偽造、偽造、偽造、偽、偽、偽、偽、偽、偽、偽、表面、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺、詐欺バンド、密輸、着せ替え、没収、ヘロイン、印刷、偽造、盗難、コカイン、違法、偽造、紙幣、メタンフェタミン、窃盗、宝石、違法、マリファナ、コイン、麻薬、宝石、ノックオフ、米国のシークレットサービス、販売、通貨、文書、衣類、靴、偽、偽造、医薬品、人工、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽造、偽善、偽善、欺瞞、欺瞞、見張り、欺瞞、偽善、偽善、不正直、偽り、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、ソフトウェア、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、欺瞞、あるいは、誤魔化す、lig、art、嘘、詐欺、cozen、chickanery、偽証、bilk、humbug、subterfuge、偽造、偽造、偽造、偽造、偽造、詐欺、詐欺、詐欺、詐欺、詐欺師、詐欺師、詐欺師、うそ、映画、不誠実、偽証、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺師、詐欺 トリック,詐欺,詐欺,詐欺師,ロゴ,ブレンチ,繕い,欺瞞,裏切り,横領,偽造,ウェイレイ,フェイク,フリムフラム,whopper,brands,pretender,discidentity,laity,laity,fibbery,prevariation,foodwink,falsibilization,faliff,decipiency,misity,mislie,blench,blench,blench,fling,fal,ifur,ifice,im,ifrt,fool,dupery,import,forlay,finagler,copy,overreach,choose,prevariate,forlie,imported,befool,fake,import,hornswoggle,blesh,undeceive,belirt],

    "murder" : [殺人,殺人,過失致死,暗殺,幼児殺害,自殺,殺人,殺人,普通法,殴打,撃退,報復,虐殺,殺人者,殺人者,殺人者,殺人者,殺人者,暴徒,ジェノサイド,カリフォルニア,破壊者,除去,マングル,殺戮,マリチド,大虐殺,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人,殺人, 処刑,肉屋,研磨,バーク,大量殺人,殺人,処刑,重罪,被害者,リンチ,斬首,パトリック,誘拐,強盗,カナダ,連続殺人犯,マトリックス,犯罪,一級殺人,逮捕,絞殺,死亡,誘拐,共謀,共犯,殺人,痴漢,容疑者,絞殺者,放火,起訴, 刑、反逆罪、投獄、失踪、強盗、検察官、恐喝、暴行、米国、被告、悪意、事前の自衛、国、侵略、オフ、人、正当化、言い訳、暗殺、殺人、殺人、殺人、殺人、抑止、更生、法律、流血、抑圧、殺人、殺人、殺人、虐殺、 リンチ,清算,ゆがみ,ゴア,除去,改ざん,ワープ,駆除業者,サーベル,毒殺,殺人者,殺人者,無法者,安楽死,殺人者,電気拷問,殺人者,電気拷問,殺人者,戦闘員,instakill,殺人可能,毒殺,犯罪化,殺せる,胎児,致死者,殺人者,ヴァギナ,電気拷問,水平化,事故,有罪判決,チームキル,有罪,チームキル,有罪,有罪,有罪,チームキル,有罪, 抹殺可能,非殺殺可能,人殺し,原インド·ヨーロッパ,根絶,うがい,乾式,撃墜,ane,anglog-unlog-gulching,bane,anglog-unlatity,裁判,sororicide,判決,無罪,嘆願,治安判事,根絶,死刑,死刑,有罪,殺人,自害,死刑執行人,写真殺す、殺す喜び、告白する、無敵、無敵、無敵、復讐、冬の殺人、容疑者、数、前例、殺人者、マニア、逮捕、事件、成文化、殺人、殺人、殺人、殺人、殺人、目撃者、無実、刺殺、有機体、殺害、窃盗、起訴、刑務所、毒素、拘留、フェミサイド、シンプソン、虐殺者、起訴、ブッチ、ベブnom,関与,毒,虐待,被告,未遂,セックス,不倫,疑惑,モック],

    "hack" : [ハッキング,ハッカー,スパイウェア,マルウェア,rasomeware,RAT,DatabaseLeaks,DBLeaks,Leak,Carding,個人情報Leak,botnet,rootkit,adware,keylogger,
                                トロイの木馬、裏口、温暖化、韓国漏れ、中国漏れ、日本漏れ],

    "weapon" : [武器,剣,銃,ミサイル,槍,火器,弾薬,砲,発射体,ライフル,ピストル,爆弾,弓,武器,武器,武器,武器,武器,武器,武器,ナイフ,ナイフ,銃,大砲,銃,ショットガン,道具,火薬,ロケット,兵器システム,第二次世界大戦,軍事,狩猟,器具,矛,青銅器,火器,戦車,戦車,機関銃,動物,消防艦,戦争,岩,岩,武器,武器又は武器、爆発物、大陸間弾道ミサイル、生物戦、装置、敵、抑止力、サイドアーム、機械、口径、射撃、要素、型式、脅威、標的、危険物、車両、軍艦、陸軍、火、大量破壊兵器、弾薬、威力、装甲、包囲兵器、世界大戦中の技術、負傷、犯罪、クラブ、斧、爪、牙, ナックルズ,火炎放射器,スラッシャー,スリング,ランス,シャフト,ブレード,ブランド,鋼,斧,トマホーク,大量破壊兵器,説得,説得,説得,説得,説得,説得,石,護身術,ヒト科,bc,黒曜石,新石器,銅,金属,サイバー兵器,ナック,w.m.d.,要塞,カタパルト,スポーク,戦車,中国,騎兵,攻撃,ハンドガン,ヨーロッパ,能力,爆発物,トライム,所持,武器,保有,兵器,兵器,兵器,兵器,兵器,兵器,兵器,兵器,兵器,兵器,保有,保有,兵器,兵器扇形,爆弾,ミサイル,必殺技,能力,リボルバー,騎士,通常,キャリー,核,バッテリー,弾道,歩兵,使用]
}

chC = {
    "child_porn" : [儿童色情, 儿童性虐待, 儿童, 国际刑警组织, 美国司法部, 色情, 视频, 录音, 未成年人, 恋童癖, 儿童美容, 欧盟委员会, 互联网手表基金会, 美国报告, 法, 照片, 雕塑, 画画, 摄影, 绘画, 动画, 强制, 审查, 服装, 萝莉控, 裸露, 相机, 马萨诸塞, 记录],

    "bitcoin" : [比特币, 区块链, 货币, 比特币网络, 密码学, 节点, 中本聪, 开源软件, 加密货币钱包, 加密货币交换, 加密货币, 公钥密码学, 以太坊, qt, 中央银行, 分布式账本, 剑桥大学, 诺贝尔纪念馆 经济科学奖, gavin andresen, 
                        丝绸之路, youtube, segwit, 海妖, 分类帐, 金融犯罪执法网络, 第四, 双花, 闪电网络, 比特币现金, 记账单位, 数字签名, 加密哈希, 兆字节, winklevoss twins , 同步, 比特币 xt, 百度, 概念验证, cve,
                        leveldb, nyse, 小额支付, openssl, andreas antonopoulos, bitinstant, unicode, 广播, 钞票, 延展性],

    "drug" : [药物, 医学, 涂料, 精神药物, 药物, 剂量, 兴奋剂, 麻醉, 注射, 制药, 药店, 镇痛药, 处方, 处方药, 醇, 下降, 吸收, 抗梅毒, 堕胎, 药物, 瘾, 药物, 阿司匹林, 烟草,大麻, 生育药, 麻醉剂, 药物, 吸烟, 魔术子弹, 通
                        用, 抗病毒药, 药​​剂师, 预防医学, 医生, 苯二氮卓类药物, 做药物, 抗惊厥药, 抗药, 仿制药, 止吐药, 丙磺舒, 抗抑郁药, 抗生素, 非法, 可卡因,大麻, 精神活性物质, 鸦片制剂, 麻醉剂, 海洛因, 安非他明, 甲基苯丙胺
                        , 药物类别, 药片, 药物, 化学结构, 作用机制, 咖啡因, 疫苗, 类固醇, 作用方式, 癌症, 解剖治疗化学分类系统, atc 代码, 生物药剂学分类系统, 致幻剂, 吸毒成瘾, 娱乐性吸毒, 麻醉药品单一公约, 谁, 非处方药, 摄入, 物质, 药剂师, 药理学, 抗组胺药, 生物, 可待因, 抗胆碱能, 抗菌, 抗凝剂, 生物医学, 慢性, 免疫学, 前药, paregoric, 餐饮, apc, 肿瘤学, 治疗, 风湿病学, 肠胃病学, 麻醉学, 安慰剂, 放射疗法, 吹气, 催眠, 药剂, 
                        松弛剂, 砷, 药典, 利尿剂, 植物, 过量, 口服, 激动剂, 过敏反应, 拮抗剂, 麻醉剂, 绊倒, 麻醉剂, 兴奋剂, 催眠剂, 毒药, 碱, 使用, 注射, 鼻息, 肾病学, 药物, 泻药, 姑息, 神经病学, 非特异性, 灵丹妙药, 治疗, pcp, 临床医生, 泻药,
                        泌尿科, 青霉素, 治疗, 方剂, 补救, 医疗, 病毒学, 皮肤科, 儿科, 紧张症, 精神病学, 妇科, 军医, 非药物, 消化性, 胰岛素, 镇静剂, 扑热息痛, 难治性, 药房, 药剂学, 神经科医生, 别嘌醇, 泰妙菌素, 抗糖尿病药,阿昔洛韦、鸦片、双硫仑、戊四唑、解痉药、驱风药、吉非罗齐、止泻药、减充血药、抗原虫药、祛痰药、医学博士、夹板药、术前用药、镇咳药、毒扁豆碱、精神病药、异丙肾上腺素、药用、异山梨醇、氨力农、 
                        抗心律失常药、增强作用、知觉、免疫抑制剂, 发热, 氯贝特, 药物, 驱虫药, 解热药, 硫糖铝, 抗高血压药, 心理医学, 抗胆碱酯酶, 情绪, 神经性, 药物后, 肠胃外, 前科, 神经精神病学, 克隆, 硫唑嘌呤, aesculapian, venesect, 创伤学, 非处方, 尿液分析, 杀虫剂, 青霉胺, 直肠学, 意识, lorfan, 麻醉, 麻醉, 游离碱, 麻醉, unin可注射的, 习惯的, 麻醉剂, 增强剂, 堕胎剂, 增效剂, 抑制剂, 扩张剂, feosol, fergon, o.d., 麻醉剂, trental, 左洛芬, 己酮可可碱, 散瞳剂, 肌肉萎缩剂, 缩瞳剂, 麻醉剂, 足病学, 罂粟碱, 血红素, 水蛭素, 抗刺激剂, 乙醇, 民族医学, 栓剂, mfm, 伪医学, 肌萎缩, 非医学, 非侵入性, 抗利尿剂, 感染, 抑制剂, 疾病学, 神奇
                        药物, 肺病学, 支气管扩张剂, panpharmacon, 尼古丁, 纳米医学, 贩运, 无色症, 血管收缩剂, 催产素, 植物医学, 继任者, 软膏, 贩运者, 数字化, 病例, 发酵, mercurialist, rubefacient, 耳科, 治疗, 艾滋病毒, 泰诺, 
                        药物, 艾滋病, 链接, 走私],

    "counterfeit" : [假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪劣, 假冒伪冒伪劣, 假冒伪冒伪冒伪冒伪冒伪冒伪冒
                        伪劣, 假冒伪冒伪冒伪冒伪冒伪劣, 假冒伪冒伪冒伪冒伪冒伪劣, 假冒伪冒伪冒伪冒伪冒伪冒伪冒伪冒伪冒伪绑匪,走私,装货,没收,海洛因,印刷,伪造,被盗,可卡因,非法,伪造者,钞票,冰毒,盗窃,珠宝,非法,大麻,硬币,麻醉品,珠
                        宝,仿冒品,美国特勤局,销售,货币,文件,服装,鞋子,虚假,伪造,制药,人工,伪造,假冒伪劣,假冒,假冒伪冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,假冒,虚假, 虚假, 
                        欺骗, 监视, 欺骗, 欺骗, 伪造, 虚假, 不诚实, 虚假, 欺骗, 欺骗, 虚假, 虚假, 虚假, 电子学, 虚假, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 软件, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗 
                        , 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗,  
                        欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 或者, 误传, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 伪造, 欺骗, 晒太阳, 天真, 欺骗, 欺骗, 玩具, 再欺骗, 耍花招, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺 
                        骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗 欺骗, 欺诈, 欺诈, 欺诈, 标志, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 欺骗, 贪污, 假冒伪劣, 欺诈, 欺诈, 欺诈, 欺诈, 欺诈, 欺诈, 华普, 品牌, 假装 
                        , 欺骗, 欺骗, 平易近人, 庸俗, 欺诈, 欺诈, 欺诈, 欺诈, 欺诈, 欺诈, 欺诈, 假冒伪劣, 假冒伪劣, 假冒, 假冒伪劣, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒伪劣, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒, 假冒 
                        , 假冒, 假冒, 假冒, rt, fool, duprey, 进口, 镶嵌, finagler, 复制, 夸张, chous, revalite, pole, fake, import, import, import, hornswogle, blesh, uncieve, birt],

    "murder" : [杀人, 杀人, 误杀, 暗杀, 杀婴, 自杀, 犯罪, 杀人, 杀人, 杀人, 杀人, 杀人, 派遣, 复仇, 屠杀, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀
                        害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀害, 杀人, 杀人, 杀人, 处决, 重罪, 私刑, 斩首, 杀害, 杀害, 绑架, 抢劫, 加拿大, 连环杀人犯, 黑客帝国, 犯罪, 一级谋杀, 逮捕, 绞杀, 死亡, 绑架, 阴谋, 共犯, 杀害, 猥亵, 嫌疑
                        人, 绞杀, 纵火, 起诉。例如, 判刑, 叛国, 监禁, 失踪, 盗窃, 起诉, 勒索, 暴行, 美国, 被告, 恶意, 自卫, 国家, 加重, 关闭, 人身, 辩解, 借口, 暗杀, 杀人, 杀人, 杀人犯, 暗杀, 威慑, 回生, 法律, 大屠杀, 镇压,  
                        屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠 
                        杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀, 屠杀,  私刑, 清算, 扭曲, 扭曲, 消除, 伪造, 篡改, 杀毒, 杀毒, 杀人犯, 被处决, 杀人, 安乐死, 杀人, 电刑, 杀人, 杀人, 机器人, 战斗人员, 注射, 毒物, 犯罪
                        , 杀人, 胎儿, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人,  
                        杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人, 杀人。 可抹杀, 不可杀人, 过失杀人, 原始印欧语, 灭绝, 胡言乱语, 干洗, 击落, 贝恩, 盎格鲁-撒克逊人, 致死, 审判, 索罗里德, 宣 
                        判, 无罪, 恳求, 消灭, 消灭, 起诉, 起诉, 指控, 屠夫, 精神病, 谋杀, 谋杀, 自卫, 处决者, 照片, 处决者杀人, 杀人, 自首, 无敌, 复仇, 冬季杀人, 嫌疑人, 数名, 判例, 杀人犯, 疯子, 被捕, 事件, 代码化, 杀人学,  
                        法律, 非暴力, 屠宰场, 尸体, 目击者, 无辜, 刺杀, 有机体, 杀人, 盗窃, 起诉, 监狱, 毒素, 拘留, 辛普森, 屠杀者, 被起诉, 被起诉, 布奇, 被起诉, 布奇。提名, 牵连, 毒害, 虐待, 被告, 未遂, 性, 通奸, 怀疑, 爱慕],

    "hack" : [黑客, 黑客, 间谍软件, 恶意软件, RAT, DataBase泄露, DB泄露, Carding, 个人信息泄露, 机器人, rootkit, 广告软件, Keylogger, 特洛伊木马, 后门, 温暖, 韩国泄露, 中国泄露, 日本泄露],

    "weapon" : [武器, 剑, 枪, 导弹, 矛, 火器, 弹药, 炮, 射弹, 步枪, 手枪, 炸弹, 弓, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 大炮, 枪, 枪, 枪, 猎枪, 工具, 火药, 火箭, 武器系统, 二战, 军事, 狩猎, 武器, 枪械, 青铜器, 
                        坦克, 战争, 战争, 动物, 消防船, 战争, 弹头, 岩石, 武器系统或武器, 爆炸物, 洲际弹道导弹, 生物战, 敌方, 威慑, 侧肩, 机枪, 口径, 射击, 元件, 类型, 威胁, 目标, 危险, 车辆, 军舰, 火种, 大规模杀伤性武器, 弹 
                        药, 弹药, 装甲, 围城武器, 第一次世界大战期间的技术, 受伤, 犯罪, 俱乐部, 牙齿, 斧头, 爪牙, 牙齿, 牙齿, 牙齿, 牙齿, 牙齿等。指节, 火焰喷射器, 铲刀, 吊索, 矛, 轴, 刃, 牌, 钢, 斧, 战斧, 劝说, 劝说, 石头,  
                        自卫, 人类, bc, 黑曜石, 新石器, 铜, 金属, 网络武器, 指节, w.d, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 防御工事, 武器, 武
                        器, 武器, 金属, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器, 武器,炸弹,导弹,致命,能力,左轮手枪,骑士,常规,运载,核武器,炮台,弹道,步兵,使用]
}

ruC = {
    "child_porn" : [детское порно, сексуальное насилие над детьми, ребенок, интерпол, министерство юстиции сша, порнография, видео, звукозапись, несовершеннолетний, педофилия, уход за детьми, европейская комиссия, фонд интернет-часов, отчеты сша, закон, фотография, скульптура, рисунок, фотография, картина, анимация, Принуждение, Цензура, одежда, Лоликон, Нагота, камера, Массачусетс, Запись],

    "bitcoin" : [Лекарство, лекарства, наркотики, психотропные лекарства, лекарства, дозы , от наркотика, injectable, фармацевтическая, аптека, инъекций, предписания по рецепту лекарства, алкоголь, брось, поглощения, antisyphilitic, требуют большего производства, успокоительное, зависимость, препарат, аспирин, табака марихуаны, от бесплодия, narcotize, наркотиков, курение, волшебной пулей., обобщенными, ВОЗ, фармоцевты, профилактическая медицина, врач, найдено содержание бензодиазепинов, употребляй наркотики, anticonvulsant, antidrug, непатентованные, противорвотное, probenecid, антидепрессантами, антибиотик, незаконный, кокаин, марихуану, психотропные вещества, опиум, наркотики, героин, амфетамин, метамфетамин, класс, лекарств, медикаментов, Химическая структура, mechan.Ism действий, кофеин, вакцины, стероиды, стиль работы, рак, анатомические терапевтического химической классификации, atc, biopharmaceutics система классификации, кетамину, наркомании, рекреационных наркотиков, конвенции о наркотических средств, которые и без рецепта, принятием, вещество, аптекарь, фармакологии, антигистамин., организм, кодеин, anticholinergic, антибактериальными, anticoagulant, биомедицины, хронические, иммунологии, prodrug, paregoric, еда, apc, онкологии, терапевтической, Понимая, гастроэнтерология, анестезиологии, плацебо, VOCAL, insufflation, деньги, агент, релаксант, arsenical, pharmacopoeia, diuretic, ботанические, передозировка, устно, agonist, anaphyla.Xis, - анестетики, поездки, анестезии, excitant, soporific, яд, базы, использование, нюхать, нефрология, лекарства, очищают, участие, неврология, неспецифические, панацеей, терапии, пневмоцистная, врач, слабительное,.
                        our, пенициллин, действенное, политики, средств правовой защиты, медицинской, вирусологии, дерматология, педиатрии, кататония, психиатрия, гинекология, врач, nondrug, peptic, инсулин, спокойно, парацетамол, тугоплавкие, диспансерное, pharmaceutic, невролог, allopurinol, tiamulin, antidiabetic, вызванные, опиум, disulfiram, pentylenetetrazol, antispasmodic. Carminative, gemfibrozil, antidiarrheal, Как, antiprotozoal, повышается, MD, лубок, premedication, antitussive, pharmacon, physostigmine, псих, isoproterenol, медицинских, isosorbide, amrinone, antiarrhythmic, potentiation, восприятие, immunosuppressant, жар, clofibrate, В, глистогонного средства, antipyretic, sucralfate, antihypertens.Тише, psychomedicine, anticholinesterase, настроение, neurotropic, postdrug, парентеральное, возможность получить последипломное, нейропсихиатрия, clonic, azathioprine, aesculapian, venesect, травматологии, nonprescription, анализ мочи, vermicide, penicillamine, колопроктология, сознание, lorfan, anaesthetize, anaesthetise, free-base, дают наркоз, uninjectable, habituate, narcotise, По.Tentiate, aborticide, synergist, для подавления dilator, feosol, fergon, поступаешь так, хмель, trental, levallorphan, pentoxifylline, mydriatic, myotic, miotic, anesthetise, podiatry, papaverine, hematinic, leechcraft, counterirritant, этанол, ethnomedicine, suppository, mfm, pseudomedical, iatrophysics, polychrest, nonmedical, атравматичной, antidiuretic., инфекции, депрессанта, nosology, wonderdrug, пульмонология, bronchodilator, panpharmacon, никотин, наномедицины, торговли, achromia, Сосуды закроются, oxytocic, phytomedicine, succedaneum, unguent, наркоторговцы, digitalize, случаях zymosis, mercurialist, rubefacient, otology, лечению, лечения, tylenol, медикаментов, средств, контрабанды],

    "drug" : [подделка, подделка, подделка, подделка, подделка, подделка, мошенничество, фальшивость, фальшивость, кража личности, нереальность, неверность, сумки, подделка, подделка, незаконная, базовая, фиктивная, синтетическая, предположительная, пинкбекка, плохая, якостная, мошенничная, неатичная, аутная, аутная, аутентичная, аутентичная, аутентичная, аутентичная, аутентичнаябанда, контрабандированная, конфискованная, героин, печать, подделка, кража, кокаин, незаконный, контрафактный, банкноты, метафетамин, кража, ювелирные изделия, незаконная, марихуана, монеты, наркотики, ювелирные изделия, нокаф,лжи, лживость, электроника, лжи, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обман, обманили, искажение, лиг, искусство, ложь, обман, обман, хитрость, хитрость, хитрость, подделка, подделка, подделка, изобретатель, обман, обман, обман, обман, обман, обман, прелюбодеяние, приманс, трюк, хитрость, неверие, обман, лжитель, лжитель, лжитель, лжитель, лжитель, лжитель, лжитель, лжитель, лжитель, лживный, лжив, лживный, лживный, лжив трюк, мошенничество, шлемер, мошенник, логотип, бленх, лживо, обман, предательство, хищность, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальсификация, фальrt, дупер, import, forlay, finagler, копирование, перехват, chouse, prevaricate, forlie, import, betool, fake, import, Hornswoggle, blesh, undeceive, belirt],

    "murder" : [убийство, убийство, убийство, убийство, младенчество, самоубийство, преступление, убийство, убийство, обычное право, удаление, младенчество, убийство, убийство, убийство, убийство, убийство, убийство, геноцид, Калифорния, мутиль, уборка, убийство, братоцид, тираницид, кровопролитие, канадский, серийный убийца, матрицид, преступник, убийца, убийца, убийца, казнь, убийство, убийство, убийство, убийство, убийство, убийство, убийство, разжигание, подозреваемые, устремление, обстрел, обстрел, приговор, измена, лишение свободы, исчезновение, грабеж, прокурор, вымогательство, нападение, объединенные государства, обвиняемый, злодеяние додумано, самооборона, страна, обострение, off, человек, оправдание, оправдание, оправдание, убийца, убийца, убийца, убийца, убийца, сдерживание, реабилитация, закон, кровопролирование, подавление, cide, убийца, убийца, убийца, линч, ликвидация, искажение, гур, ликвидация, фальсификация, warp, истребитель, сабер, ядовитый, убийца, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, горизонтализация, убийство, убийство, убийство, убийство, убийство, уничтожить, обстрелить, сбивать, расстрелять, расстрелять, расстрелять, расстрелять, расстрелять, расстрелять, расстрелять, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать, убивать.убийство, убийство, убийство, убийство, убийство, убийство, убийство, убийство, закон, демократия, бойня, убийство, тело, свидетель, невинный, устремление, организм, убийство, кражи, обвинение, тюрьма, токсин, арест, феницид, убийство, обвиняемый, но, веноменклатура, вовлечение, ядовито, злоупотребление, обвиняемые, попытка, секс, прелюбодеяние, подозрение, амок],

    "hack" : [взлома, хакер, шпионское ПО, вредоносные программы, rasomeware, RAT, DataBases утечки, DB утечки, утечка, картование, Ликвидация личной информации, ботнет, rootkit, adware, keylogger,
                        Троянская лошадь, задняя дверь, теплые, корея утечки, китайские утечки, Япония утечки],

    "weapon" : [оружие, меч, оружие, ракета, копье, огнестрельное оружие, боеприпасы, артиллерия, снаряжение, пистолет, бомба, лук, оружие, оружие, оружие, пушка, пушка, ружье, ружье, ракета, система оружия, война, вторая мировая война, военная, охота, инструмент, пик, бронзовый возраст, огнестрелка, танк, война, рок, оружие, рокили, оружие, взрывная, межконтинентальная баллистическая ракета, биологическая война, устройство, враг, сдерживающий, боковая техника, калибр, стрельба, элемент, тип, угроза, цель, опасный, автомобиль, военный корабль, армия, огонь, оружие массового уничтожения, боеприпасы, оружие, осада, технологии во время мировой войны i, травмы, клуба, зубов, ось, ось, кл, кл, кл, кл, кл., ручки, огнестрелитель, шлинг, ланец, вал, лезвие, марка, сталь, хатхет, томахавк, wmd, убеждение, суазия, камень, самозащита, гоминиды, bc, obsidian, неолитичный, медь, металл, киберруз, ручки, w.m.d., укрепления, катапина, рука, колес, речи, речи, речи, речи, речи, речи, речи, речи, речи, речи, речи, речи, речи,сенал, бомбы, ракеты, смертельные, способность, револьвер, рыцари, обычные, носить, ядерный, аккумулятор, баллистический, пехотный, использование]
}